src/main/scala/no/ndla/searchapi/SearchApiProperties.scala, src/main/scala/no/ndla/searchapi/controller/SearchController.scala, src/main/scala/no/ndla/searchapi/integration/Elastic4sClient.scala, src/main/scala/no/ndla/searchapi/model/api/GroupSearchResult.scala, src/main/scala/no/ndla/searchapi/model/api/MultiSearchResult.scala, src/main/scala/no/ndla/searchapi/model/search/SearchableTaxonomyContext.scala, src/main/scala/no/ndla/searchapi/model/taxonomy/TaxonomyFilter.scala, src/main/scala/no/ndla/searchapi/service/search/ArticleIndexService.scala, src/main/scala/no/ndla/searchapi/service/search/IndexService.scala, src/main/scala/no/ndla/searchapi/service/search/LearningPathIndexService.scala, src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala, src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala, src/test/scala/no/ndla/searchapi/controller/SearchControllerTest.scala, src/test/scala/no/ndla/searchapi/model/search/SearchableArticleTest.scala, src/test/scala/no/ndla/searchapi/model/search/SearchableLearningPathTest.scala, src/test/scala/no/ndla/searchapi/model/search/SearchableTaxonomyContextTest.scala, src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
Also updates query-params `resource-types` and `subjects` to take ids (ex: `urn:subject:1`) rather than subject name
=> #914: Implements group search

src/main/scala/no/ndla/searchapi/controller/SearchController.scala, src/main/scala/no/ndla/searchapi/model/search/settings/MultiDraftSearchSettings.scala, src/main/scala/no/ndla/searchapi/model/search/settings/SearchSettings.scala, src/main/scala/no/ndla/searchapi/service/search/DraftIndexService.scala, src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala, src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala, src/test/scala/no/ndla/searchapi/TestData.scala, src/test/scala/no/ndla/searchapi/controller/SearchControllerTest.scala, src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala
Also moves all settings (including query and noteQuery) to
MultiDraftSearchSettings rather than taking them in separate parameters
for the matchingQuery method.
=> #830: Implements noteQuery for MultiDraftSearch

src/main/scala/no/ndla/searchapi/service/search/LearningPathSearchService.scala, src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
resolves https://github.com/NDLANO/Issues/issues/1182
=> Uses correct field for alt and url in metaImage for multiSearch learningpaths

src/main/scala/no/ndla/searchapi/service/search/TaxonomyFiltering.scala, src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
Dersom det søkes på fleire ressurstyper fra ndla-frontend så forventes det at utvalget innsnevres og ikkje utvides. Derfor må vi endre søket til å ha must i stedet for should for dette filteret.
=> Need to use must if several resourcetypes

src/main/scala/no/ndla/searchapi/SearchApiProperties.scala, src/main/scala/no/ndla/searchapi/integration/SearchApiClient.scala, src/main/scala/no/ndla/searchapi/service/search/IndexService.scala
Virker som database access i de andre api'ene som tar lang tid (Noen ganger over 20 sekunder for å hente ut 1000 drafts).
Går selvfølgelig an å undersøke hvorfor spørringene tar lang tid (Har sikkert noe med at vi gjør en nested spørring for å finne bare siste revision av drafts), men vet ikke om vi gidder å bruke tid på det jeg.
Denne PR'en gjør indeksering i mindre chunks og flere tråder i tillegg til å increase timeouten.
Det gjorde at indekseringsjobben i test gikk fra 13 til 10 minutter.
Om vi ikke syns kompleksiteten er verdt det så vil også bare å øke timeouten fikse "problemet", men da vil indekseringen naturligvis ta like lang tid.
Hva tenker dere @gunnarvelle @N4G1 ?
=> Higher timeout and multiple threads for indexing in smaller chunks

src/main/scala/no/ndla/searchapi/model/domain/article/Article.scala, src/test/scala/no/ndla/searchapi/TestData.scala, src/test/scala/no/ndla/searchapi/integration/ArticleApiClientTest.scala
Article-api trigger indeksering ved publisering, og når search-api returnerer resultat av indeksering klarer ikkje article-api å parse svaret fordi published ikkje finnes i responsen. Verdien brukes ikkje til noko her, den berre tas i mot og returneres.
=> Must specify published to prevent error in article-api indexing

src/main/scala/no/ndla/searchapi/model/api/ApiTaxonomyContext.scala, src/main/scala/no/ndla/searchapi/model/api/TaxonomyContextFilter.scala, src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
Legger på filterid fordi dette trengs for å kunne presentere urler med filter i søkeresultat. I dag returneres kun navnet på filteret og det gjør det vanskelig å ha korrekt url.
=> Add filterid to filter results

src/main/scala/no/ndla/searchapi/controller/SearchController.scala, src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala, src/test/scala/no/ndla/searchapi/TestData.scala, src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala, src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
Fixes NDLANO/Issues#2236
En ressurs som er knytta til to subjects, en synlig og en usynlig, blir indeksert i søket med begge kontekstene tilgjengelig fordi filtering på synlighet kun tar høgde for subject i path-parameteren, og kun på den pathen som kjem først. Dersom synlig path kjem først blir begge kontekstene med, men om den usynlige pathen kjem først vises den uten kontekster.
Endringa bryr seg ikkje om path-parameteren, men sjekker heller om subject for conteksten er synlig i filteringa.
=> Filter out contexts for invisible subjects

src/main/scala/no/ndla/searchapi/SearchApiProperties.scala, src/main/scala/no/ndla/searchapi/controller/SearchController.scala, src/main/scala/no/ndla/searchapi/model/search/settings/MultiDraftSearchSettings.scala, src/main/scala/no/ndla/searchapi/model/search/settings/SearchSettings.scala, src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala, src/test/scala/no/ndla/searchapi/TestData.scala, src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala
=> #2226: Only create initial scroll-context when provided with '0', 'start', 'first' or 'initial'

src/main/scala/no/ndla/searchapi/model/search/SearchableLanguageFormats.scala, src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala, src/test/scala/no/ndla/searchapi/TestData.scala, src/test/scala/no/ndla/searchapi/model/search/SearchableArticleTest.scala
- Handle null as LanguageValue in serializer to handle taxonomy filter name = null (And other potential `null` values in LanguageValue's)
- Optimize some taxonomy converter functions for better performance when indexing
=> #2279: Handle null as LanguageValue in serializer to handle taxonomy filter name = null

.gitignore, src/main/scala/no/ndla/searchapi/model/api/MultiSearchSummary.scala, src/main/scala/no/ndla/searchapi/service/search/IndexService.scala, src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala, src/main/scala/no/ndla/searchapi/service/search/SearchService.scala, src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala, src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
Fixes NDLANO/Issues#2289
Kanskje fixes NDLANO/Issues#2291
- Legger til elasticsearch score og highlights til søkeresultatene
- Kan testes ved å spinne opp api'et og gjøre et søk og se på responsen :smile: 
- Gjør decompounding av ord litt strengere som vil gi oss færre resultater, men syns det er vanskelig å vite hva vi egentlig har lyst på her (Ref https://github.com/NDLANO/Issues/issues/2291#issuecomment-716526026)
Eksempel på scoring og highlights:
```
{
"id": 18327,
...
"score": 39.289825439453125,
"highlights": [
{
"field": "embedAttributes.nn",
"matches": [
"Publikum på <em>fotballkamp</em> i England. Foto."
]
},
{
"field": "content.nb",
"matches": [
"Hun kan for eksempel observere hvordan deltakerne på en <em>fotballkamp</em> kler seg, hvor ofte elever tar opp"
]
},
{
"field": …
```
=> #2291 + #2289: Adds scoring and highlights to search hits and stricter decompounding

src/main/scala/no/ndla/searchapi/controller/SearchController.scala, src/main/scala/no/ndla/searchapi/model/api/GroupSearchResult.scala, src/main/scala/no/ndla/searchapi/model/api/MultiSearchResult.scala, src/main/scala/no/ndla/searchapi/model/api/MultiSearchSummary.scala, src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
Relates to NDLANO/Issues#2310
- Legger til paths på `MultiSearchSummary` for at gruppesøket skal være bakoverkompatibelt.
- Bruker `MultiSearchSummary` i gruppesøket også.
=> #2310: Return entire objects when group searching

src/main/scala/no/ndla/searchapi/controller/SearchController.scala, src/main/scala/no/ndla/searchapi/model/search/settings/SearchSettings.scala, src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala, src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala, src/main/scala/no/ndla/searchapi/service/search/TaxonomyFiltering.scala, src/test/scala/no/ndla/searchapi/TestData.scala, src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
Relates to NDLANO/Issues#2310
- Lager grupper for `context-types` i gruppesøket også (`standard`/`topic-article`/`learningpath`)
- Legger til en parameter for å ha med en gruppe uten resourceType.
`/search-api/v1/search/group/?resource-types=urn%3Aresourcetype%3AsubjectMaterial&include-without-resource-types=true&context-types=topic-article`
gir dette resultatet (med treff i `results` array'ene):
```
[
{
"totalCount": 8802,
"page": 1,
"pageSize": 10,
"language": "all",
"results": [ ... ],
"suggestions": [],
"resourceType": "urn:resourcetype:subjectMaterial"
},
{
"totalCount": 2463,
"page": 1,
"pageSize": 10,
"language": "all",
"results": [ ... ],
"suggestions": [],
"resourceType": "topic-article"
},
{
"totalCount": 4085,
"page": 1,
"pageSize": 10,
"language": "all",
"results": [ ... ], …
```
=> #2310: Includes 'context-types' as groups for group search and param for no resource-type

src/main/scala/no/ndla/searchapi/controller/SearchController.scala, src/main/scala/no/ndla/searchapi/model/api/MultiSearchResult.scala, src/main/scala/no/ndla/searchapi/model/api/MultiSearchTermsAggregation.scala, src/main/scala/no/ndla/searchapi/model/domain/SearchResult.scala, src/main/scala/no/ndla/searchapi/model/domain/TermAggregation.scala, src/main/scala/no/ndla/searchapi/model/search/settings/MultiDraftSearchSettings.scala, src/main/scala/no/ndla/searchapi/model/search/settings/SearchSettings.scala, src/main/scala/no/ndla/searchapi/service/search/FakeAgg.scala, src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala, src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala, src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala, src/main/scala/no/ndla/searchapi/service/search/SearchService.scala, src/test/scala/no/ndla/searchapi/TestData.scala, src/test/scala/no/ndla/searchapi/controller/SearchControllerTest.scala, src/test/scala/no/ndla/searchapi/service/search/SearchServiceTest.scala
Relates to NDLANO/Issues#2125
Legger til query-param `aggregate-paths` som tar in en path i indeksen som aggregeres og vises i søke-resultatet
Feks:
GET `/search-api/v1/search/editorial/?aggregate-paths=contexts.contextType`
```
{
"totalCount": 23329,
"page": 1,
"pageSize": 10,
"language": "all",
"results": [
... // Vanlige resultater
],
"suggestions": [],
"aggregations": [
{
"field": "contexts.contextType",
"sumOtherDocCount": 0,
"docCountErrorUpperBound": 0,
"values": [
{
"value": "standard",
"count": 27589
},
{
"value": "topic-article",
"count": 2620
},
{
"value": "learningpath",
"count": 1288
}
]
}
]
}
```
Koden er litt små-kompleks så om dere finner noe som ikke er kommentert som er vanskelig å lese, så sleng en kommentar så skal jeg prøve så godt jeg kan å forklare den (og …
=> Adds building, using, and returning termsAggregations from paths

.travis.yml, src/test/scala/no/ndla/searchapi/service/search/ArticleIndexServiceTest.scala, src/test/scala/no/ndla/searchapi/service/search/IndexServiceTest.scala, src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala, src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
Installerer awscli og bruker den for å logge inn i ECR-repoet for å få tilgang til search-engine imaget som brukes i testene.
=> Login to ECR repo on travis to not cancel tests

src/main/scala/no/ndla/searchapi/controller/SearchController.scala, src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala, src/test/scala/no/ndla/searchapi/controller/SearchControllerTest.scala, src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
Relates to NDLANO/Issues#2434
Fikser så søk med search-context=initial (og de andre) fungerer som forventet og returnerer en search-context header
Søk uten search-context returnerer ingenting
=> #2434: Fix search-context=initial (++)

src/main/scala/no/ndla/searchapi/controller/SearchController.scala, src/main/scala/no/ndla/searchapi/model/search/SearchableArticle.scala, src/main/scala/no/ndla/searchapi/model/search/SearchableDraft.scala, src/main/scala/no/ndla/searchapi/model/search/settings/MultiDraftSearchSettings.scala, src/main/scala/no/ndla/searchapi/model/search/settings/SearchSettings.scala, src/main/scala/no/ndla/searchapi/service/search/ArticleIndexService.scala, src/main/scala/no/ndla/searchapi/service/search/DraftIndexService.scala, src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala, src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala, src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala, src/test/scala/no/ndla/searchapi/TestData.scala, src/test/scala/no/ndla/searchapi/model/search/SearchableArticleTest.scala, src/test/scala/no/ndla/searchapi/model/search/SearchableDraftTest.scala, src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala, src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
Fixes NDLANO/Issues#2403
Fixes NDLANO/Issues#2425
Søk på artikler utvides med ny funksjonalitet:
1. Søk på artikkel-id på query-parameter skal returnere artikkel med samme id.
2. Søk på embed data-attributter (data-videoid, data-resource, data-resource_id, data-url) på query-parameter skal returnere artikler som har en embed som matcher.
3. Søk på embed data-attributter kan også gjøres med to nye parametre. embedResource (data-resource) og embedId (data-videoid, data-resource_id, data-url).
Annet:
- De fire nye data-attributtene skal være indeksert som nøkler og kun gi resultat ved nøyaktig match.
- Har skrevet nye tester. 
- Vil gjerne ha tilbakemelding på bruk av boost-parameter. Satte denne til 3 for de nye parameterne, men usikker på både bruk og hva som er mest riktig verdi her.
=> 2403 2425 add indexing and search on more embed attributes

src/main/scala/no/ndla/searchapi/controller/SearchController.scala
Fixes NDLANO/Issues#2403. Glemte å legge til nye parametre i /editorial-søk.
Opprinnelig PR: https://github.com/NDLANO/search-api/pull/135
@gunnarvelle: embedResource og embedId skal ikke være en del av /draft søk? Fjerner i så fall dette også.
=> Add embedResource and embedId params to /editorial search

src/main/scala/no/ndla/searchapi/model/search/SearchableArticle.scala, src/main/scala/no/ndla/searchapi/model/search/SearchableDraft.scala, src/main/scala/no/ndla/searchapi/service/search/ArticleIndexService.scala, src/main/scala/no/ndla/searchapi/service/search/DraftIndexService.scala, src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala, src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala, src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala, src/main/scala/no/ndla/searchapi/service/search/SearchService.scala, src/test/scala/no/ndla/searchapi/TestData.scala, src/test/scala/no/ndla/searchapi/model/search/SearchableArticleTest.scala, src/test/scala/no/ndla/searchapi/model/search/SearchableDraftTest.scala, src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala, src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
Et par fikser for som ikke ble implementert i https://github.com/NDLANO/search-api/pull/135
Hva som er fikset:
- Forklaring-embed id var ikke tidligere indeksert. Har lagt til "data-content-id" i `getEmbedIds` for å fikse dette.
- Søk på `embedId `og `embedResource `ble ikke tidligere matchet mot visuelt element. Dette er lagt til i funksjonene `getEmbedResourcesToIndex `og `getEmbedIdsToIndex`
- embedId og embedResource søkes nå i med hensyn til language-parameter. Har laget en type query `langTermQueryFunc` for å støtte dette.
Har skrevet noen nye tester.
=> bugfix add indexing visual element and concept

src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala, src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala, src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
Fixes NDLANO/Issues#2483
Søk på embedId gir også treff i metabilde.
H5P-bugen relatert til denne PR-en må løses i article-api. 
PR: https://github.com/NDLANO/article-api/pull/350
=> 2483 metaimage as embedid search

src/main/scala/no/ndla/searchapi/service/search/IndexService.scala, src/main/scala/no/ndla/searchapi/service/search/SearchService.scala, src/test/scala/no/ndla/searchapi/TestData.scala, src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala, src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
Fixes NDLANO/Issues#2449
I prod får man nå feil resultat dersom man forsøker eksakt med spesialtegn eller mellomrom. Dette kan feks være `"test-tekst"`eller `"test tekst"`. Den behandler spesialtegnene likt som mellomrom og man får derfor flere treff enn nødvendig. Det skal også fungere å kombinere operatorer og eksakt søk. Feks: `"test-tekst" +- feiltekst` som gir resultater som innholder `"test-tekst", `men som ikke har `feiltekst` i seg.
Har nå kommet fram til en løsning som ikke brekker de gamle testene.
=> Exact search works with operators

.gitignore, build.sbt, src/main/scala/no/ndla/searchapi/controller/SearchController.scala, src/main/scala/no/ndla/searchapi/model/search/settings/MultiDraftSearchSettings.scala, src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala, src/test/scala/no/ndla/searchapi/TestData.scala, src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala
- Defaults to filter statuses based only on current
- Adds `filter-other-statuses` flag to allow filtering both current and other.
=> #2527: Defaults to filter statuses based only on current

src/main/scala/no/ndla/searchapi/model/search/EmbedValues.scala, src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala, src/test/scala/no/ndla/searchapi/TestData.scala, src/test/scala/no/ndla/searchapi/model/search/SearchableArticleTest.scala, src/test/scala/no/ndla/searchapi/model/search/SearchableDraftTest.scala, src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala, src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
En enkelt embed kan inneholde flere ider (feks id og url). 
Endrer ID i EmbedValues til å være en liste for å støtte dette.
Gjelder også concept-api: https://github.com/NDLANO/concept-api/pull/84
=> Search on embed id now supports multiple ids in one embed

build.sbt, src/main/scala/no/ndla/searchapi/JettyLauncher.scala, src/main/scala/no/ndla/searchapi/SearchApiProperties.scala, src/main/scala/no/ndla/searchapi/service/StandaloneIndexing.scala, src/main/scala/no/ndla/searchapi/service/search/IndexService.scala, src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
- Legger til `STANDALONE_INDEXING_ENABLED` miljøvariabel, denne:
- Starter indeksering ved oppstart
- Spinner _ikke_ opp webserveren
- Avslutter prosessen når indeksering avslutter (eller feiler)
- Nye indekser opprettes med `number_of_replicas=0` for raskere indeksering (Den settes til 1 igjen når indekseringen fullfører)
=> Adds option which enables standalone indexing

src/main/scala/no/ndla/searchapi/model/api/ApiTaxonomyContext.scala, src/main/scala/no/ndla/searchapi/model/search/SearchableTaxonomyContext.scala, src/main/scala/no/ndla/searchapi/model/taxonomy/SubjectTopicConnection.scala, src/main/scala/no/ndla/searchapi/model/taxonomy/TopicResourceConnection.scala, src/main/scala/no/ndla/searchapi/model/taxonomy/TopicSubtopicConnection.scala, src/main/scala/no/ndla/searchapi/service/search/IndexService.scala, src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala, src/test/scala/no/ndla/searchapi/TestData.scala, src/test/scala/no/ndla/searchapi/service/search/SearchConverterServiceTest.scala
Indekserer relevance fra koblingsobjektet på taksonomikontekst. Dette kjem i tillegg til relevance som er på filter og som forsvinner snart.
=> Adding relevance to searchable context.

src/main/scala/no/ndla/searchapi/ComponentRegistry.scala, src/main/scala/no/ndla/searchapi/controller/NdlaController.scala, src/main/scala/no/ndla/searchapi/controller/SearchController.scala, src/main/scala/no/ndla/searchapi/integration/FeideApiClient.scala, src/main/scala/no/ndla/searchapi/integration/SearchApiClient.scala, src/main/scala/no/ndla/searchapi/model/api/Error.scala, src/main/scala/no/ndla/searchapi/model/domain/article/Article.scala, src/main/scala/no/ndla/searchapi/model/domain/article/Availability.scala, src/main/scala/no/ndla/searchapi/model/domain/article/RelatedContentLink.scala, src/main/scala/no/ndla/searchapi/model/search/SearchableArticle.scala, src/main/scala/no/ndla/searchapi/model/search/settings/SearchSettings.scala, src/main/scala/no/ndla/searchapi/service/search/ArticleIndexService.scala, src/main/scala/no/ndla/searchapi/service/search/IndexService.scala, src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala, src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala, src/test/scala/no/ndla/searchapi/TestData.scala, src/test/scala/no/ndla/searchapi/TestEnvironment.scala, src/test/scala/no/ndla/searchapi/controller/SearchControllerTest.scala, src/test/scala/no/ndla/searchapi/integration/ArticleApiClientTest.scala, src/test/scala/no/ndla/searchapi/model/search/SearchableArticleTest.scala, src/test/scala/no/ndla/searchapi/service/search/ArticleIndexServiceTest.scala, src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
Relates to NDLANO/Issues#2609
Filtrerer ut artikler som har `student` eller `teacher` availability basert på rettigheter fra feide accessTokenet som kan sendes med til controlleren for `/group/` og `/` endepunktene i `FeideAuthorization` headeren.
Kan tenkes at det er litt teit å ha feide-auth logikken i selve controlleren nå, men jeg ville holde det utenfor `SearchService` og syns det var litt drastisk med et helt eget service lag for å gjøre en bitteliten request (Om noen er uenig så er jeg åpen for å endre det :smile:).
=> #2609: Filter out teacher and student available articles in multisearch

src/main/scala/no/ndla/searchapi/model/domain/ReindexResult.scala, src/main/scala/no/ndla/searchapi/service/StandaloneIndexing.scala, src/main/scala/no/ndla/searchapi/service/search/IndexService.scala
Fixes NDLANO/Issues#2732
Standalone indekseringen vil nå sende antall feil til slack dersom det
finnes flere enn 0 feilede dokumenter i resultatet fra indekseringen.
=> #2732: Send slack error message if any of the attempted indexed documents fail

src/main/scala/no/ndla/searchapi/service/search/ArticleIndexService.scala, src/main/scala/no/ndla/searchapi/service/search/DraftIndexService.scala, src/main/scala/no/ndla/searchapi/service/search/IndexService.scala, src/main/scala/no/ndla/searchapi/service/search/LearningPathIndexService.scala, src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala, src/test/scala/no/ndla/searchapi/service/search/ArticleIndexServiceTest.scala, src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceAtomicTest.scala, src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala, src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceAtomicTest.scala, src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala, src/test/scala/no/ndla/searchapi/service/search/SearchConverterServiceTest.scala
Fixes NDLANO/Issues#2847
Denne PR'en tillater GREP å feile ved inkrementell indeksering.
Kan testes ved å spinne opp api'et med `GREP_API_HOST=noesomikkefunker.com` og gjøre en enkel indekseringsrequest å sjekke at indekseringen går igjennom.
Og teste at bulk indeksering fortsatt feiler i samme situasjon (`POST /intern/index`)
---
Eksempel på request for indeksering av enkelt dokuemnt: 
`POST /intern/draft/`
```json
{"id":123,"revision":23,"status":{"current":"QUEUED_FOR_LANGUAGE","other":["IMPORTED"]},"title":[{"title":"En kul tittel","language":"nb"}],"content":[{"content":"<section><p>Noe kult innhold</p></section>","language":"nb"}],"copyright":{"license":"CC-BY-SA-4.0","origin":"","creators":[{"type":"Writer","name":"Jonas"}],"processors":[],"rightsholders":[]},"tags":[{"tags":["årua" …
```
=> #2847: Allow GREP to fail when indexing single documents

src/main/scala/no/ndla/searchapi/controller/SearchController.scala
Brukte lenger tid enn jeg vil innrømme på å skjønne hvorfor søket plutselig feila når jeg var innlogget i feide :smile:
=> Handle `Bearer`-prefix in FeideAuthorization header
