src/main/scala/no/ndla/searchapi/model/search/SearchableLearningPath.scala
src/main/scala/no/ndla/searchapi/service/search/DraftIndexService.scala
src/main/scala/no/ndla/searchapi/service/search/LearningPathIndexService.scala
src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
src/test/scala/no/ndla/searchapi/TestData.scala
src/test/scala/no/ndla/searchapi/model/search/SearchableLearningPathTest.scala
src/test/scala/no/ndla/searchapi/service/search/LearningPathSearchServiceTest.scala
src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala
src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala

Also makes learningpaths without taxonomy show up in MultiDraftSearch
resolves https://github.com/NDLANO/Issues/issues/1069

#1069: Makes authors searchable

---

src/main/scala/no/ndla/searchapi/SearchApiProperties.scala
src/main/scala/no/ndla/searchapi/controller/SearchController.scala
src/main/scala/no/ndla/searchapi/integration/SearchApiClient.scala
src/main/scala/no/ndla/searchapi/integration/TaxonomyApiClient.scala
src/main/scala/no/ndla/searchapi/service/search/IndexService.scala

connects to https://github.com/NDLANO/Issues/issues/1143

#1143: Adds missing filtering options for group search

---

src/main/scala/no/ndla/searchapi/integration/Elastic4sClient.scala

connects to https://github.com/NDLANO/Issues/issues/1177

#1177: Sets longer timeout for elastic4s client

---

src/main/scala/no/ndla/searchapi/controller/InternController.scala
src/main/scala/no/ndla/searchapi/controller/NdlaController.scala
src/main/scala/no/ndla/searchapi/model/api/Error.scala
src/main/scala/no/ndla/searchapi/model/domain/learningpath/LearningPath.scala

connects to NDLANO/Issues#1221

#1221: Adds endpoints for indexing and deleting single documents

---

src/main/scala/no/ndla/searchapi/SearchApiProperties.scala

connects to NDLANO/Issues#1127

#1127: Adds configurability for internal api urls

---

src/main/scala/no/ndla/searchapi/controller/InternController.scala
src/main/scala/no/ndla/searchapi/controller/SearchController.scala
src/main/scala/no/ndla/searchapi/integration/SearchApiClient.scala
src/main/scala/no/ndla/searchapi/integration/TaxonomyApiClient.scala
src/main/scala/no/ndla/searchapi/model/api/ArticleResult.scala
src/main/scala/no/ndla/searchapi/model/api/AudioResult.scala
src/main/scala/no/ndla/searchapi/model/api/ImageAltText.scala
src/main/scala/no/ndla/searchapi/model/api/ImageResult.scala
src/main/scala/no/ndla/searchapi/model/api/LearningPathIntroduction.scala
src/main/scala/no/ndla/searchapi/model/api/LearningpathResult.scala
src/main/scala/no/ndla/searchapi/service/ConverterService.scala
src/main/scala/no/ndla/searchapi/service/search/ArticleIndexService.scala
src/main/scala/no/ndla/searchapi/service/search/DraftIndexService.scala
src/main/scala/no/ndla/searchapi/service/search/IndexService.scala
src/main/scala/no/ndla/searchapi/service/search/LearningPathIndexService.scala
src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
src/test/scala/no/ndla/searchapi/service/search/ArticleIndexServiceTest.scala
src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala
src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
src/test/scala/no/ndla/searchapi/service/search/SearchConverterServiceTest.scala

connects to NDLANO/Issues#1391
- Optimizes fetching taxonomy (Only fetch it once, and fetch it in parallel)
- Adds language to `/search-api/v1/search/draft` where applicable

#1391: Adds language for media search

---

src/main/scala/no/ndla/searchapi/controller/NdlaController.scala
src/main/scala/no/ndla/searchapi/controller/SearchController.scala
src/main/scala/no/ndla/searchapi/model/search/SearchableTaxonomyFilter.scala
src/main/scala/no/ndla/searchapi/model/search/settings/MultiDraftSearchSettings.scala
src/main/scala/no/ndla/searchapi/model/search/settings/SearchSettings.scala
src/main/scala/no/ndla/searchapi/service/search/IndexService.scala
src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
src/test/scala/no/ndla/searchapi/TestData.scala
src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala
src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala

connects to NDLANO/Issues#1404

#1404: Adds filtering options for relevance.

---

src/main/scala/no/ndla/searchapi/controller/SearchController.scala
src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
src/main/scala/no/ndla/searchapi/service/search/TaxonomyFiltering.scala
src/test/scala/no/ndla/searchapi/TestData.scala
src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala
src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
src/test/scala/no/ndla/searchapi/service/search/SearchConverterServiceTest.scala

#1480: Relevance filtering with relation to levels

---

src/main/scala/no/ndla/searchapi/SearchApiProperties.scala
src/main/scala/no/ndla/searchapi/controller/NdlaController.scala
src/main/scala/no/ndla/searchapi/controller/SearchController.scala
src/main/scala/no/ndla/searchapi/model/api/Error.scala
src/main/scala/no/ndla/searchapi/model/api/MultiSearchResult.scala
src/main/scala/no/ndla/searchapi/model/domain/SearchResult.scala
src/main/scala/no/ndla/searchapi/model/search/settings/SearchSettings.scala
src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
src/main/scala/no/ndla/searchapi/service/search/SearchService.scala
src/test/scala/no/ndla/searchapi/TestData.scala
src/test/scala/no/ndla/searchapi/controller/SearchControllerTest.scala
src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala
src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala

connects to NDLANO/Issues#1489

#1489: Allows scrolling by returning a search-context that can be used to scroll

---

src/main/scala/no/ndla/searchapi/controller/NdlaController.scala
src/main/scala/no/ndla/searchapi/controller/SearchController.scala
src/main/scala/no/ndla/searchapi/integration/SearchApiClient.scala
src/main/scala/no/ndla/searchapi/model/domain/draft/ArticleStatus.scala
src/main/scala/no/ndla/searchapi/model/domain/draft/Draft.scala
src/main/scala/no/ndla/searchapi/model/domain/draft/EditorNote.scala
src/main/scala/no/ndla/searchapi/model/domain/draft/Status.scala
src/main/scala/no/ndla/searchapi/model/search/SearchableDraft.scala
src/main/scala/no/ndla/searchapi/model/search/settings/MultiDraftSearchSettings.scala
src/main/scala/no/ndla/searchapi/service/search/DraftIndexService.scala
src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
src/test/scala/no/ndla/searchapi/TestData.scala
src/test/scala/no/ndla/searchapi/model/search/SearchableDraftTest.scala
src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala

connects to NDLANO/Issues#1518
Legger også til støtte for nye `EditorNote` formatet (med bakoverkompabilitet)

#1518: Adds draft search option to filter by draft status

---

src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala

Added notes in regular search. Upped boost on title to three.

Added search for notes in content search

---

src/main/scala/no/ndla/searchapi/controller/SearchController.scala
src/main/scala/no/ndla/searchapi/model/search/settings/SearchSettings.scala
src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
src/main/scala/no/ndla/searchapi/service/search/TaxonomyFiltering.scala
src/test/scala/no/ndla/searchapi/TestData.scala
src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala

Connects to NDLANO/issues#1595
The name context-filter is already used in frontend and graphql-api.

Added parameter for filtering on resourcetypes.

---

src/main/scala/no/ndla/searchapi/controller/SearchController.scala
src/main/scala/no/ndla/searchapi/model/domain/draft/Draft.scala
src/main/scala/no/ndla/searchapi/model/domain/draft/EditorNote.scala
src/main/scala/no/ndla/searchapi/model/search/SearchableDraft.scala
src/main/scala/no/ndla/searchapi/model/search/settings/MultiDraftSearchSettings.scala
src/main/scala/no/ndla/searchapi/service/search/DraftIndexService.scala
src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
src/test/scala/no/ndla/searchapi/TestData.scala
src/test/scala/no/ndla/searchapi/model/search/SearchableDraftTest.scala
src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala

Søker etter bruker-id fra Auth0

Search for userid for drafts

---

src/main/scala/no/ndla/searchapi/model/domain/draft/Draft.scala
src/main/scala/no/ndla/searchapi/model/search/SearchableArticle.scala
src/main/scala/no/ndla/searchapi/model/search/SearchableDraft.scala
src/main/scala/no/ndla/searchapi/model/search/SearchableLearningPath.scala
src/main/scala/no/ndla/searchapi/model/search/SearchableLearningStep.scala
src/main/scala/no/ndla/searchapi/model/search/SearchableTaxonomyContext.scala
src/main/scala/no/ndla/searchapi/model/search/SearchableTaxonomyFilter.scala
src/main/scala/no/ndla/searchapi/model/search/SearchableTaxonomyResourceType.scala
src/main/scala/no/ndla/searchapi/model/search/SearchableTaxonomyTopic.scala
src/main/scala/no/ndla/searchapi/model/search/settings/SearchSettings.scala
src/main/scala/no/ndla/searchapi/service/search/DraftIndexService.scala
src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
src/test/scala/no/ndla/searchapi/TestData.scala
src/test/scala/no/ndla/searchapi/model/search/SearchableDraftTest.scala
src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala

Depends on NDLANO/draft-api/pull/154

#1886: Makes old notes searchable on drafts

---

src/main/scala/no/ndla/searchapi/controller/SearchController.scala
src/main/scala/no/ndla/searchapi/model/domain/article/Article.scala
src/main/scala/no/ndla/searchapi/model/domain/draft/Draft.scala
src/main/scala/no/ndla/searchapi/model/search/SearchableArticle.scala
src/main/scala/no/ndla/searchapi/model/search/SearchableDraft.scala
src/main/scala/no/ndla/searchapi/model/search/settings/MultiDraftSearchSettings.scala
src/main/scala/no/ndla/searchapi/model/search/settings/SearchSettings.scala
src/main/scala/no/ndla/searchapi/service/search/ArticleIndexService.scala
src/main/scala/no/ndla/searchapi/service/search/DraftIndexService.scala
src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
src/test/scala/no/ndla/searchapi/TestData.scala
src/test/scala/no/ndla/searchapi/integration/ArticleApiClientTest.scala
src/test/scala/no/ndla/searchapi/model/search/SearchableArticleTest.scala
src/test/scala/no/ndla/searchapi/model/search/SearchableDraftTest.scala
src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala
src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala

https://github.com/NDLANO/Issues/issues/2039

renamed competences to grepCodes and testing pacts with different branch

---

src/main/scala/no/ndla/searchapi/model/api/MultiSearchSummary.scala
src/main/scala/no/ndla/searchapi/model/api/Status.scala
src/main/scala/no/ndla/searchapi/model/search/SearchableDraft.scala
src/main/scala/no/ndla/searchapi/model/search/Status.scala
src/main/scala/no/ndla/searchapi/service/search/DraftIndexService.scala
src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
src/test/scala/no/ndla/searchapi/model/search/SearchableDraftTest.scala

https://github.com/NDLANO/Issues/issues/2109
Testet at article ikke returnerer status, mens learningpath og draft gjør.

added status to response for drafts and learningpaths

---

src/main/scala/no/ndla/searchapi/model/api/MultiSearchResult.scala
src/main/scala/no/ndla/searchapi/model/api/MultiSearchSuggestion.scala
src/main/scala/no/ndla/searchapi/model/domain/Language.scala
src/main/scala/no/ndla/searchapi/model/domain/SearchResult.scala
src/main/scala/no/ndla/searchapi/service/search/ArticleIndexService.scala
src/main/scala/no/ndla/searchapi/service/search/IndexService.scala
src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
src/main/scala/no/ndla/searchapi/service/search/SearchService.scala
src/test/scala/no/ndla/searchapi/controller/SearchControllerTest.scala
src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala

Støtte for søkeforslag i search-api.
Nynorsk tokenizer: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-lang-analyzer.html#norwegian-analyzer + https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-stemmer-tokenfilter.html
Phrase suggester: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html#phrase-suggester

Suggester for search queries

---

build.sbt
src/main/scala/no/ndla/searchapi/caching/Memoize.scala
src/main/scala/no/ndla/searchapi/controller/InternController.scala
src/main/scala/no/ndla/searchapi/controller/NdlaController.scala
src/main/scala/no/ndla/searchapi/integration/GrepApiClient.scala
src/main/scala/no/ndla/searchapi/integration/TaxonomyApiClient.scala
src/main/scala/no/ndla/searchapi/service/search/IndexService.scala
src/test/scala/no/ndla/searchapi/caching/MemoizeTest.scala
src/test/scala/no/ndla/searchapi/service/search/SearchConverterServiceTest.scala

Fixes NDLANO/Issues#2153 (Forhåpentligvis)

#2153: Memoize calls to taxonomy and grep api

---

src/main/scala/no/ndla/searchapi/service/search/LearningPathIndexService.scala
src/main/scala/no/ndla/searchapi/service/search/SearchService.scala
src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala

Legger til suggestions for både title og content.

Added suggestion for content. Had to add empty field for learningpath.

---

src/main/scala/no/ndla/searchapi/model/api/MultiSearchSummary.scala
src/main/scala/no/ndla/searchapi/model/search/SearchableArticle.scala
src/main/scala/no/ndla/searchapi/model/search/SearchableDraft.scala
src/main/scala/no/ndla/searchapi/service/search/ArticleIndexService.scala
src/main/scala/no/ndla/searchapi/service/search/DraftIndexService.scala
src/main/scala/no/ndla/searchapi/service/search/IndexService.scala
src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
src/test/scala/no/ndla/searchapi/TestData.scala
src/test/scala/no/ndla/searchapi/model/search/SearchableArticleTest.scala
src/test/scala/no/ndla/searchapi/model/search/SearchableDraftTest.scala
src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
src/test/scala/no/ndla/searchapi/service/search/SearchConverterServiceTest.scala

NDLANO/Issue#2204
Adds article traits for displaying in search results in new design.

Index traits in articles based on content.

---

src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
src/test/scala/no/ndla/searchapi/TestData.scala
src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
src/test/scala/no/ndla/searchapi/service/search/SearchConverterServiceTest.scala

Gjør det mulig å søke på tittel til kompetansemål og få treff på artikler som har målet.

Added search for grep code text.

---

src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
src/test/scala/no/ndla/searchapi/TestData.scala
src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala
src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala

Fixes NDLANO/Issues#2224
Det må være mulig å filtrer drafts på usynlige subjects.

Let invisible subjects be searchable in draft

---

src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
src/test/scala/no/ndla/searchapi/TestData.scala
src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala
src/test/scala/no/ndla/searchapi/service/search/SearchConverterServiceTest.scala

Fixes NDLANO/Issues#2225
Fikser det slik at du får treff på forfattere av gamle notes.

Make it possible to search for all note editors

---

src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
src/test/scala/no/ndla/searchapi/service/search/SearchConverterServiceTest.scala

Fixes NDLANO/Issues#2255
Indekserer en kontekst per filter, i og med at filter skal behandles som fag i nytt design.

One context per filter

---

src/main/scala/no/ndla/searchapi/SearchApiProperties.scala
src/main/scala/no/ndla/searchapi/controller/InternController.scala
src/main/scala/no/ndla/searchapi/integration/ArticleApiClient.scala
src/main/scala/no/ndla/searchapi/integration/AudioApiClient.scala
src/main/scala/no/ndla/searchapi/integration/DraftApiClient.scala
src/main/scala/no/ndla/searchapi/integration/ImageApiClient.scala
src/main/scala/no/ndla/searchapi/integration/LearningPathApiClient.scala
src/main/scala/no/ndla/searchapi/integration/SearchApiClient.scala
src/main/scala/no/ndla/searchapi/service/ApiSearchService.scala
src/main/scala/no/ndla/searchapi/service/search/IndexService.scala
src/test/scala/no/ndla/searchapi/integration/ArticleApiClientTest.scala
src/test/scala/no/ndla/searchapi/integration/DraftApiClientTest.scala
src/test/scala/no/ndla/searchapi/integration/LearningpathApiClientTest.scala
src/test/scala/no/ndla/searchapi/service/ApiSearchServiceTest.scala

Inneholder også noen av optimaliseringene fra https://github.com/NDLANO/search-api/pull/116

Better logging when failing indexing

---

src/main/scala/no/ndla/searchapi/controller/SearchController.scala
src/main/scala/no/ndla/searchapi/model/api/GroupSearchResult.scala
src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala

Legger til aggregeringer på gruppesøk.

Aggs on group search

---

src/main/scala/no/ndla/searchapi/model/search/SearchableTaxonomyContext.scala
src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
src/test/scala/no/ndla/searchapi/TestData.scala

I tilfelle relevanceid er null i søket.

make relevanceid optional

---

src/main/scala/no/ndla/searchapi/SearchApiProperties.scala
src/main/scala/no/ndla/searchapi/SearchSwagger.scala
src/main/scala/no/ndla/searchapi/model/domain/Language.scala
src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
src/main/scala/no/ndla/searchapi/service/search/SearchService.scala
src/test/scala/no/ndla/searchapi/TestData.scala
src/test/scala/no/ndla/searchapi/integration/LearningpathApiClientTest.scala

NDLANO/Issues#2656
Legger til rette for konfigurering av ndla-verdier.

Extracting ndla-values as params

---

src/main/scala/no/ndla/searchapi/service/search/IndexService.scala

Fixes NDLANO/Issues#2834
Kan testes ved å se at en index med feil ikke blir byttet ut, når man kjører standalone indeksering, eller kaller `POST /intern/index` endepunktet.
Standalone indeksering kan startes ved å ha `STANDALONE_INDEXING_ENABLED=true` satt i miljøvariabler
Må legge inn en manuell feil dersom du ikke har _veldig_ flaks med testingen :smile: 
Feks ved å tryne en av chunk-fetchene med en:
```scala
if(page == 2) return Future.failed(new RuntimeException("test"))
```

#2834: Only replace index if every indexing request succeeded
